obstacle_avoidance:
  safety_distance: 0.5
  slow_distance: 1.0
  emergency_stop_distance: 0.2

velocity_limits:
  max_linear_speed: 0.3
  max_angular_speed: 0.5
  min_linear_speed: 0.05
  min_angular_speed: 0.1

sensors:
  use_lidar: false
  use_ultrasonic: true
  use_vision: true

ultrasonic:
  max_range: 4.0
  min_range: 0.02
  field_of_view: 0.26
  sensors:
    - name: front
      trig: 23
      echo: 24
      frame_id: ultrasonic_front
    - name: left
      trig: 17
      echo: 27
      frame_id: ultrasonic_left
    - name: right
      trig: 5
      echo: 6
      frame_id: ultrasonic_right
    - name: rear
      trig: 22
      echo: 10
      frame_id: ultrasonic_rear

path_planning:
  algorithm: a_star
  resolution: 0.05
  planning_timeout: 5.0

exploration:
  enabled: true
  frontier_based: true
  goal_tolerance: 0.2

person_following:
  enabled: true
  follow_distance: 1.5
  min_distance: 0.8
  max_distance: 3.0
  lost_timeout: 5.0
  face_confidence_threshold: 0.7

face_recognition:
  enabled: true
  model: dlib_hog
  known_faces_path: "data/known_faces"
  save_new_faces: true
  auto_name_new_faces: false
  recognition_tolerance: 0.6
